name: Deploy to AWS Elastic BeanStalk
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' '*node_modules*' '*.env*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: AWS-BeanStalk-Pipeline
          environment_name: AWS-BeanStalk-Pipeline-env
          version_label: "${{ github.sha }}-$(date +%Y%m%d%H%M%S)"
          existing_bucket_name: elasticbeanstalk-ap-south-1-729468324884
          region: ap-south-1
          deployment_package: deploy.zip
